import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "./component/header";
import Footer from "./component/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Header/>
        
        <main className="p-5">

        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
